USE QLGV
 ---PHAN III---
 ---Cau 1---
 SELECT
	MAHV, (HO+TEN) HOTEN, NGSINH, HOCVIEN.MALOP
FROM
	HOCVIEN, LOP
WHERE
	HOCVIEN.MAHV = LOP.TRGLOP
---Cau 2---
SELECT 
	HOCVIEN.MAHV, (HO +' '+TEN) HOTEN, LANTHI, DIEM 
FROM 
	KETQUATHI, HOCVIEN
WHERE
	KETQUATHI.MAHV = HOCVIEN.MAHV
	AND MAMH = 'CTRR'
	AND MALOP = 'K12'
ORDER BY
	TEN, HO
---Cau 3---
SELECT
	HOCVIEN.MAHV, (HO +' '+TEN) HOTEN, TENMH
FROM
	KETQUATHI, MONHOC, HOCVIEN
WHERE
	KETQUATHI.MAMH = MONHOC.MAMH
	AND KETQUATHI.MAHV = HOCVIEN.MAHV
	AND LANTHI = 1 AND KQUA = 'Dat'
---Cau 4---
SELECT HOCVIEN.MAHV, (HO + ' ' + TEN) HOTEN
FROM HOCVIEN, KETQUATHI
WHERE 
HOCVIEN.MAHV = KETQUATHI.MAHV
AND MALOP ='K11'
AND MAMH = 'CTRR'
AND KQUA = 'Khong Dat'
AND LANTHI = 1
---Cau 5---
SELECT DISTINCT
HOCVIEN.MAHV, (HO + ' ' + TEN) HOTEN
FROM 
HOCVIEN, KETQUATHI
WHERE
HOCVIEN.MAHV = KETQUATHI.MAHV
AND MALOP like 'K%'
AND MAMH = 'CTRR'
AND NOT EXISTS
(SELECT*FROM KETQUATHI
WHERE
KQUA = 'Dat'
AND MAMH = 'CTRR'
AND MAHV = HOCVIEN.MAHV)
---Cau 6---
SELECT DISTINCT TENMH
FROM
	MONHOC, GIAOVIEN, GIANGDAY
WHERE
	MONHOC.MAMH = GIANGDAY.MAMH
	AND GIAOVIEN.MAGV = GIANGDAY.MAGV
	AND HOTEN = 'Tran Tam Thanh'
	AND HOCKY = 1 AND NAM = 2006
	---PHAN II---
	---Cau 1---
UPDATE GIAOVIEN
SET HESO = 0.2 + HESO
WHERE MAGV IN (SELECT TRGKHOA FROM KHOA)
---Cau 2---
UPDATE HOCVIEN
SET DIEMTB =
(
	SELECT AVG(DIEM)
	FROM KETQUATHI
	WHERE LANTHI = (SELECT MAX(LANTHI) FROM KETQUATHI KQ WHERE MAHV = KETQUATHI.MAHV GROUP BY MAHV)
	GROUP BY MAHV
	HAVING MAHV = HOCVIEN.MAHV
)
---Cau 3---
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN 
(
	SELECT MAHV
	FROM KETQUATHI
	WHERE LANTHI = 3 AND DIEM < 5
)
---Cau 4---
-- II.4 Cập nhật giá trị cho cột XEPLOAI trong quan hệ HOCVIEN như sau: 
-- Nếu DIEMTB >= 9 thì XEPLOAI = ”XS”
-- Nếu 8 <= DIEMTB < 9 thì XEPLOAI = “G”
-- Nếu 6.5 <= DIEMTB < 8 thì XEPLOAI = “K”
-- Nếu 5 <= DIEMTB < 6.5 thì XEPLOAI = “TB” 
-- Nếu DIEMTB < 5 thì XEPLOAI = ”Y” 
UPDATE HOCVIEN
SET XEPLOAI =
(
	CASE 
		WHEN DIEMTB >= 9 THEN 'XS'
		WHEN DIEMTB >= 8 AND DIEMTB < 9 THEN 'G'
		WHEN DIEMTB >= 6.5 AND DIEMTB < 8 THEN 'K'
		WHEN DIEMTB >= 5 AND DIEMTB < 6.5 THEN 'TB'
		WHEN DIEMTB < 5 THEN 'Y'
	END
)
