USE QuanLyBanHang

---Cau 30---
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA IN (
SELECT DISTINCT TOP (3) GIA 
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
ORDER BY GIA DESC
)
---Cau 31---
SELECT TOP (3) MAKH, HOTEN, 
RANK() OVER (ORDER BY DOANHSO DESC) AS DS_RANK  
FROM KHACHHANG
---Cau 32---
SELECT COUNT(MASP) AS TONGSPTQ
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
 ---Cau 33---
 SELECT NUOCSX, COUNT(MASP) AS TONGSOSANPHAN
 FROM SANPHAM
 GROUP BY NUOCSX
 ---Cau 34---
 SELECT NUOCSX, MAX(GIA) AS MAX, MIN(GIA) AS MIN, AVG(GIA) AS AVG
 FROM SANPHAM
 GROUP BY NUOCSX
 ---35---
 SELECT NGHD, SUM(TRIGIA) AS DOANHTHU
 FROM HOADON
 GROUP BY NGHD
 ---Cau 36---
SELECT MASP, COUNT(DISTINCT MASP) AS TONGSO
FROM SANPHAM
WHERE MASP IN(SELECT MASP
FROM CTHD C INNER JOIN HOADON H
ON C.SOHD = H.SOHD
WHERE MONTH(NGHD) = 10 AND YEAR(NGHD) = 2006)
GROUP BY MASP
---Cau 37---
SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHTHU
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD) 
---Cau 38---
SELECT *
FROM HOADON
WHERE SOHD IN(SELECT SOHD
FROM CTHD
WHERE SL >= 4)
---Cau 39---
SELECT *
FROM HOADON
WHERE SOHD IN(SELECT SOHD
FROM CTHD C INNER JOIN SANPHAM S
ON C.MASP = S.MASP
WHERE NUOCSX = 'VIET NAM' AND SL >= 3)
---Cau 40---
SELECT MAKH, HOTEN
FROM KHACHHANG
WHERE MAKH = (SELECT TOP (1) MAKH
FROM HOADON
GROUP BY MAKH
ORDER BY COUNT(DISTINCT SOHD) DESC
)
---Cau 41---
SELECT TOP 1 MONTH(NGHD) AS THANG_DOANHSO_MAX
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
ORDER BY SUM(TRIGIA) DESC
---Cau 42---
SELECT MASP, TENSP
FROM SANPHAM
WHERE MASP = (SELECT TOP 1 MASP
FROM CTHD
GROUP BY MASP
ORDER BY SUM(SL) DESC)
--- Cau 43*---
SELECT MASP, TENSP, NUOCSX
FROM SANPHAM AS SP
WHERE GIA >=( SELECT MAX(GIA) FROM SANPHAM
WHERE SP.NUOCSX = NUOCSX )
---Cau 44---
SELECT NUOCSX 
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) >=3
---Cau 45---
SELECT MAKH, HOTEN FROM (
	SELECT TOP 10 HD.MAKH, HOTEN, DOANHSO, RANK() OVER (ORDER BY COUNT(HD.MAKH) DESC) RANK_SOLAN 
	FROM HOADON HD INNER JOIN KHACHHANG KH 
	ON HD.MAKH = KH.MAKH
	GROUP BY HD.MAKH, HOTEN, DOANHSO
	ORDER BY DOANHSO DESC
) A
WHERE RANK_SOLAN = 1
                                                           ---HET---



