USE	QuanLyBanHang
                                               ---Phan III---
---Cau 1---
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
 ---Cau 2---
 SELECT MASP, TENSP
 FROM SANPHAM
 WHERE DVT IN('cay','quyen')
 ---cau 3---
 SELECT MASP, TENSP
 FROM SANPHAM
 WHERE MASP LIKE'B%01'
 ---Cach 2---
 SELECT MASP, TENSP
FROM SANPHAM
WHERE SUBSTRING(MASP, 1,1) ='B' AND SUBSTRING(MASP, 3,2)='01'
 ---Cau 4---
SELECT MASP, TENSP, NUOCSX
FROM SANPHAM
WHERE NUOCSX ='Trung Quoc' AND GIA BETWEEN 30000 AND 40000
---Cau 5---
SELECT MASP, TENSP, NUOCSX
FROM SANPHAM
WHERE (NUOCSX = 'Trung Quoc' OR NUOCSX = 'Thai Lan') AND GIA BETWEEN 30000 AND 40000
---Cau 6---
SELECT SOHD, TRIGIA
FROM HOADON
WHERE MONTH(NGHD) = 1 AND YEAR(NGHD) = 2007 AND DAY(NGHD) BETWEEN 1 AND 2
---Cau 7---
SELECT SOHD, TRIGIA
FROM HOADON
WHERE MONTH(NGHD) = 1 AND YEAR(NGHD) = 2007 ORDER BY NGHD ASC, TRIGIA DESC
---Cau 8---
SELECT K.MAKH, HOTEN
FROM KHACHHANG K INNER JOIN HOADON H
ON K.MAKH = H.MAKH
WHERE NGHD ='1/1/2007'
---Cau 9---
SELECT SOHD, TRIGIA
FROM HOADON H INNER JOIN NHANVIEN N
ON H.MANV = N.MANV
WHERE NGHD = '10/28/2006'
AND HOTEN = 'NGUYEN VAN B'
---Cau 10---
SELECT SANPHAM.MASP, TENSP
FROM CTHD INNER JOIN SANPHAM ON CTHD.MASP =
SANPHAM.MASP
INNER JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
INNER JOIN KHACHHANG ON KHACHHANG.MAKH =
HOADON.MAKH
WHERE KHACHHANG.HOTEN = 'Nguyen Van A' AND
MONTH(HOADON.NGHD) = 10 AND YEAR(HOADON.NGHD) =
2006
---Cach 2---
---Cau 11---
SELECT SOHD
FROM CTHD
WHERE MASP IN('BB01', 'BB02') 
---Cau 12---
SELECT SOHD
FROM CTHD
WHERE MASP IN('BB01', 'BB02')
AND SL BETWEEN 10 AND 20
---Cau 13---
SELECT SOHD
FROM CTHD A
WHERE A.MASP ='BB01'
AND SL BETWEEN 0 AND 20
AND EXISTS(SELECT*
 FROM CTHD B
 WHERE B.MASP = 'BB02'
 AND SL BETWEEN 10 AND 20
 AND A.SOHD = B.SOHD)
 ---Cau 14---
 SELECT DISTINCT MASP, TENSP
FROM SANPHAM 
WHERE NUOCSX = 'TRUNG QUOC'
UNION
SELECT DISTINCT S.MASP, TENSP
FROM SANPHAM S INNER JOIN CTHD C
ON S.MASP = C.MASP
INNER JOIN HOADON H
ON C.SOHD = H.SOHD
WHERE NGHD ='1/1/2007'
---Cau 15---
SELECT S.MASP, TENSP
FROM SANPHAM S
WHERE NOT EXISTS(SELECT * 
FROM SANPHAM S2 INNER JOIN CTHD C
ON S2.MASP = C.MASP
AND S2.MASP = S.MASP)
                                          ---Phan II---
---Cau 2---
SELECT * INTO SANPHAM1 FROM SANPHAM
SELECT * INTO KHACHHANG1 FROM KHACHHANG

---Cau 3---
UPDATE SANPHAM1
SET GIA = GIA + 0.05*GIA
WHERE NUOCSX = 'Thai Lan'
---Cau 4---
UPDATE SANPHAM1
SET GIA = GIA + 0.05*GIA
WHERE NUOCSX = 'Trung Quoc' AND GIA <=10000
---Cau 5---
UPDATE KHACHHANG1
 SET LOAIKH ='Vip'
 WHERE (NGDK<'2011/1/1' AND DOANHSO>=10000000) OR (NGDK>'2011/1/1' AND DOANHSO >=2000000)

